# Generated by Django 4.0.3 on 2022-05-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=0.0, max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
