# Generated by Django 4.0.3 on 2022-05-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_movie_genre_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='African', max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
