# Generated by Django 4.0.3 on 2022-05-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_movie_genre_alter_movie_image_alter_movie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
    ]
